name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for submitting your issue. :thumbsup: We are really glad to have you here."
        pr-message: "Thanks for submitting your first pull request :star:. The approver will look in to this PR."
