name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: ${{ github.actor != 'renovate[bot]' }}

    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          "Thanks @${{ github.actor }} for submitting your issue. :thumbsup: We are really glad to have you here."

        pr-message: "Thanks @${{ github.actor }} for submitting your first pull request :star:. The approver will look in to this PR."
